#!/usr/bin/env bash

set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  separate-source.sh --out PATH [options]

Export a source-only Chromium tree from the current checkout. The export keeps
normal source files, including flattened v8/skia/angle/etc. contents, and
excludes Git metadata plus host toolchain/generated outputs.

Options:
  --src PATH       Source checkout to export. Default: ../src relative to sync/.
  --out PATH       Output directory for the exported source tree. Required.
  --force          Remove the output directory first if it already exists.
  --dry-run        Show what would be copied without writing files.
  -h, --help       Show this help.

The script never deletes .git directories from the original checkout.
EOF
}

log() {
  printf '==> %s\n' "$*"
}

die() {
  printf 'ERROR: %s\n' "$*" >&2
  exit 1
}

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
src_dir="$(cd "$script_dir/../src" 2>/dev/null && pwd -P || true)"
out_dir=""
force=0
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --src)
      src_dir="${2:-}"
      shift 2
      ;;
    --src=*)
      src_dir="${1#*=}"
      shift
      ;;
    --out)
      out_dir="${2:-}"
      shift 2
      ;;
    --out=*)
      out_dir="${1#*=}"
      shift
      ;;
    --force)
      force=1
      shift
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "Unknown option: $1"
      ;;
  esac
done

[[ -n "$src_dir" ]] || die "Missing source directory. Pass --src."
[[ -d "$src_dir" ]] || die "Source directory does not exist: $src_dir"
[[ -f "$src_dir/DEPS" ]] || die "Not a Chromium src checkout: $src_dir"
[[ -n "$out_dir" ]] || die "Missing --out PATH."

if ! command -v rsync >/dev/null 2>&1; then
  die "rsync is required for source export."
fi

src_dir="$(cd "$src_dir" && pwd -P)"
mkdir -p "$(dirname "$out_dir")"
out_parent="$(cd "$(dirname "$out_dir")" && pwd -P)"
out_dir="$out_parent/$(basename "$out_dir")"

case "$out_dir" in
  "$src_dir"|"$src_dir"/*)
    die "Output directory must not be inside the source checkout."
    ;;
esac

if [[ -e "$out_dir" ]]; then
  if [[ "$force" != "1" ]]; then
    die "Output already exists: $out_dir. Pass --force to replace it."
  fi
  if [[ "$dry_run" != "1" ]]; then
    log "Removing existing output directory"
    rm -rf "$out_dir"
  fi
fi

rsync_args=(
  -a
  --delete
  --info=stats2

  # Git metadata from the top-level src repo and nested dependency repos.
  --exclude='/.git/'
  --exclude='/**/.git/'
  --exclude='/.gitmodules'
  --exclude='/DEPS.toolchain'

  # Build outputs and gclient temporary directories.
  --exclude='/out/'
  --exclude='/out*/'
  --exclude='/**/_gclient_*/'
  --exclude='/_bad_scm/'

  # Local hook/build metadata. These files are regenerated by gclient hooks,
  # GN, Siso, or reclient and should not be tracked in the company source repo.
  --exclude='/.landmines'
  --exclude='/build/config/gclient_args.gni'
  --exclude='/build/config/siso/.sisoenv'
  --exclude='/build/config/siso/.sisorc'
  --exclude='/build/config/siso/backend_config/backend.star'
  --exclude='/build/util/LASTCHANGE'
  --exclude='/build/util/LASTCHANGE.committime'
  --exclude='/build/util/LASTCHANGE_commit_position.h'
  --exclude='/buildtools/reclient/NOTICE'
  --exclude='/buildtools/reclient/scandeps_server.sym'
  --exclude='/buildtools/reclient_cfgs/reproxy.cfg'
  --exclude='/buildtools/reclient_cfgs/chromium-browser-clang/'
  --exclude='/buildtools/reclient_cfgs/python/'
  --exclude='/buildtools/reclient_cfgs/win-cross/'
  --exclude='/chromeos/tast_control.gni'
  --exclude='/gpu/config/gpu_lists_version.h'
  --exclude='/gpu/webgpu/DAWN_VERSION'
  --exclude='/gpu/webgpu/dawn_commit_hash.h'
  --exclude='/skia/ext/skia_commit_hash.h'
  --exclude='/testing/location_tags.json'

  --exclude='/chrome/build/pgo_profiles/'
  --exclude='/third_party/devtools-frontend/src/third_party/esbuild/'
  --exclude='/third_party/devtools-frontend/src/third_party/rollup_libs/'
  --exclude='/third_party/devtools-frontend/src/node_modules/@rollup/rollup-*/'
  --exclude='/third_party/gperf/'
  --exclude='/third_party/microsoft_dxheaders/src/'
  --exclude='/third_party/microsoft_webauthn/src/'
  --exclude='/third_party/openxr/src/'
  --exclude='/third_party/perl/'

  # Linux sysroots and platform toolchain payloads.
  --exclude='/build/linux/debian_*-sysroot/'
  --exclude='/third_party/dawn/build/linux/debian_*-sysroot/'
  --exclude='/third_party/llvm-build/'
  --exclude='/third_party/rust-toolchain/'
  --exclude='/third_party/node/linux/'
  --exclude='/third_party/node/mac/'
  --exclude='/third_party/node/mac_arm64/'
  --exclude='/third_party/node/win/'
  --exclude='/third_party/node/node_modules/'
  --exclude='/buildtools/linux64-format/'
  --exclude='/buildtools/mac-format/'
  --exclude='/buildtools/mac_arm64-format/'
  --exclude='/buildtools/win-format/'
  --exclude='/third_party/depot_tools/.cipd_bin/'
  --exclude='/third_party/depot_tools/.cipd_client_cache/'

  # Common generated/cache files.
  --exclude='/.gclient_entries'
  --exclude='/.gcs_entries'
  --exclude='/.cipd/'
  --exclude='/**/.cipd/'
  --exclude='/**/__pycache__/'
  --exclude='/**/*.pyc'
  --exclude='/**/*.pyo'
)

if [[ "$dry_run" == "1" ]]; then
  rsync_args+=(--dry-run --itemize-changes)
fi

log "Exporting source-only tree"
log "Source: $src_dir"
log "Output: $out_dir"
rsync "${rsync_args[@]}" "$src_dir/" "$out_dir/"

if [[ "$dry_run" == "1" ]]; then
  log "Dry run complete"
  exit 0
fi

if find "$out_dir" -name .git -print -quit | grep -q .; then
  die "Export still contains .git metadata."
fi

cat >"$out_dir/SOURCE_EXPORT_INFO.txt" <<EOF
Generated by sync/separate-source.sh
Source checkout: $src_dir
Generated at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')

This tree intentionally excludes Git metadata, build outputs, gclient temporary
directories, and host toolchain payloads. Run sync-toolchain.py after cloning
this source tree from the company repository on each build platform.

Important: Chromium .gitignore files ignore many flattened third_party source
dependencies. When importing or updating the company source repository, stage
the export with:

  git add -A -f .
EOF

log "Source export complete"
log "You can initialize a company Git repository in: $out_dir"
log "When importing/updating it, use: git add -A -f ."
